services:
  test:
    build: .
    volumes:
      - ./src:/opt/tollkeeper/src
      - ./tests:/opt/tollkeeper/tests
      - ./packages:/opt/tollkeeper/packages
      - ./test_dags:/opt/tollkeeper/test_dags
