name: Feature request
description: Propose something new or a change to existing behavior
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: What feature are you proposing?
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: What problem does this solve for you? What are you unable to do today?
    validations:
      required: true

  - type: textarea
    id: proposed-implementation
    attributes:
      label: Proposed implementation
      description: Rough sketch of the API or approach, if you have one.
    validations:
      required: false

  - type: checkboxes
    id: pr
    attributes:
      label: Are you willing to submit PR?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - label: Yes I am willing to submit a PR!
